blank_issues_enabled: false
contact_links:
  - name: 🚀 First-Class Support
    url: https://github.com/sponsors/matkoch?frequency=one-time&sponsor=matkoch
    about: Use a one-time or monthly sponsorship to receive best support
  - name: 💬 Chat on Slack
    url: https://slofile.com/slack/nukebuildnet
    about: Get in touch with the whole community
  - name: 🗞 Follow on Twitter
    url: https://twitter.com/nukebuildnet
    about: Learn about features and other material